### PR TITLE
formatting: markdown is weird about nested lists

### PR DESCRIPTION
**Pull request by zx2c4**
While github deals with the invalid markdown, other implementations such as markdown_py do not.

### CODE REVIEW

**Comment by trevp** [comment]
I'm not sure this is invalid, github markdown says to use 2 spaces, and Markdown.pl handles it fine?

**Comment by zx2c4** [comment]
The first level can use 2 spaces, and then the next ones need 4. This is written in the spec. Markdown.pl is somewhat permissive, as is Github, but the main Python implementation isn't so happy with this spec violation. Here's how it renders it:

http://git.zx2c4.com/noise/about/

You'll notice there are some big problems around the parts fixed in this patch.

**Comment by trevp** [comment]
"The first level can use 2 spaces, and then the next ones need 4."

Could you point me at where this is stated?

**Comment by zx2c4** [comment]
I might be mistaken about this, actually. But it appears that in either case the indentation in this section of the file is inconsistent and doesn't render correctly on all implementations. Perhaps the problem is that 3 spaces were used for a level instead of 2 or 4?

**Comment by infinity0** [comment]
FWIW I've found reStructuredText to be more predictable and powerful than markdown. It's only a tiny little bit more complex. In my experience markdown wastes more time if you're writing a document longer than about 500 words. Github supports rendering it automatically, you just need to name it `.rst` instead of `.md`, and you can use `pandoc(1)` to make the initial conversion easier.

**Comment by zx2c4** [comment]
Are you suggesting that you're going to convert noise.md to noise.rst and do things in rst going forward? Or is this merely a suggestion to have me render the markdown document using pandoc, to work around the bugs that this pull request trivially fixes?

**Comment by trevp** [comment]
Thanks for thoughts Ximin, markdown is easy and more widely known, so replacing it isn't a priority.  At some point later I'll look into prettifying this, and might consider things like that.

Didn't know you were paying attention, you should join the mailing list and give spec feedback...

**Comment by infinity0** [comment]
Heh, I am just lightly following it. Thanks for the invite, I'll likely pop back in the future to look at it in more detail. :)

**Comment by trevp** [comment]
Pandoc was having trouble with this, so fixed it to 4-space indent for sublists.

**Pull request closed without merging**
